{{- $config := .Values.config -}}
{{- if .Values.global.config }}
{{- $config := merge .Values.config .Values.global.config -}}
{{- end }}
{{- if and $config.secret.create $config.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $config.secret.name | default "vsphere-cloud-secret" }}
  labels:
    app: {{ template "cpi.name" . }}
    vsphere-cpi-infra: secret
    component: cloud-controller-manager
    {{- include "labels.common" $ | nindent 4 }}
  namespace: {{ .Release.Namespace }}
stringData:
  {{ $config.vcenter }}.username: {{ $config.username | quote }}
  {{ $config.vcenter }}.password: {{ $config.password | quote }}
{{- end -}}
