apiVersion: v2
appVersion: 1.29.0
description: A Helm chart for vSphere Cloud Provider Interface Manager (CPI)
name: cloud-provider-for-vsphere
version: 1.29.0
keywords:
  - vsphere
  - vmware
  - cloud
  - provider
  - cpi
home: https://github.com/kubernetes/cloud-provider-vsphere
icon: https://raw.githubusercontent.com/kubernetes/cloud-provider-vsphere/master/docs/vmware_logo.png
sources:
  - https://github.com/kubernetes/cloud-provider-vsphere
annotations:
  application.giantswarm.io/team: "rocket"