apiVersion: v2
# repo: kubernetes/cloud-provider-vsphere
appVersion: 1.34.0
description: A Helm chart for vSphere Cloud Provider Interface Manager (CPI)
name: cloud-provider-for-vsphere
# repo: kubernetes/cloud-provider-vsphere
version: 1.34.0
keywords:
  - vsphere
  - vmware
  - cloud
  - provider
  - cpi
home: https://github.com/giantswarm/cloud-provider-vsphere-app
icon: https://raw.githubusercontent.com/kubernetes/cloud-provider-vsphere/master/docs/vmware_logo.png
sources:
  - https://github.com/giantswarm/cloud-provider-vsphere-app
annotations:
  application.giantswarm.io/team: "rocket"
maintainers:
  - name: Team Rocket
    email: team-rocket@giantswarm.io
