apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: "{{ .Release.Namespace }}"

patchesStrategicMerge:
  - patches/daemonset-images.yaml
  - patches/deployment-images.yaml
  - patches/internal-feature-states-topology.yaml
resources:
  - input/vsphere-csi-driver.yaml