apiVersion: v1
data:
  {{- if .Values.rangeGlobal }}
  range-global: {{ .Values.rangeGlobal }}
  {{- end }}
  {{- if .Values.cidrGlobal }}
  cidr-global: {{ .Values.cidrGlobal }}
  {{- end }}
kind: ConfigMap
metadata:
  name: kubevip
  namespace: {{ .Release.Namespace | default "kube-system" }}
  labels:
    {{- include "labels.common" $ | nindent 4 }}
