config:
  clusterId: ""
  vcenter: ""
  username: ""
  password: ""
  datacenter: ""
  region: ""
  zone: ""
  thumbprint: ""

controllerDeployment:
  replicas: 1

storageClass:
  enabled: true
  delete:
    isDefault: true
    vcdStorageProfileName: "vSAN Default Storage Policy"
    fileSystem: "ext4"
  retain:
    isDefault: false
    vcdStorageProfileName: "vSAN Default Storage Policy"
    fileSystem: "ext4"

topologyPreferentialDatastores:
  enabled: false

containerSecurityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
