apiVersion: v1
data:
  async-query-volume: "true"
  block-volume-snapshot: "true"
  cnsmgr-suspend-create-volume: "true"
  csi-auth-check: "true"
  csi-migration: "true"
  csi-windows-support: "false"
  improved-csi-idempotency: "true"
  improved-volume-topology: "true"
  list-volumes: "false"
  max-pvscsi-targets-per-vm: "true"
  online-volume-extend: "true"
  pv-to-backingdiskobjectid-mapping: "false"
  topology-preferential-datastores: "false"
  trigger-csi-fullsync: "false"
  use-csinode-id: "true"
kind: ConfigMap
metadata:
  labels:
    {{- include "labels.common" $ | nindent 4 }}
  name: internal-feature-states.csi.vsphere.vmware.com
  namespace: '{{ .Release.Namespace }}'
