global:
  config:
    enabled: true
    clusterId: ""
    vcenter: ""
    username: ""
    password: ""
    datacenter: ""
    region: ""
    zone: ""
    # openssl s_client -connect <vcenter>:443 < /dev/null 2>/dev/null | openssl x509 -fingerprint -sha1 -noout
    thumbprint: ""

  podSecurityStandards:
    enforced: false

cloud-provider-for-vsphere:
  daemonset:
    image: docker.io/giantswarm/cpi-vsphere-manager

kube-vip:
  enabled: true
  env:
    vip_interface: "ens192"
  image:
    repository: docker.io/giantswarm/kube-vip
    tag: "v0.6.3"
  nameOverride: kube-vip-svc-lb
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
    operator: Exists
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists

kube-vip-cloud-provider:
  enabled: true
  rangeGlobal: ""
  cidrGlobal: ""
  image:
    repository: docker.io/giantswarm/kube-vip-cloud-provider
    tag: "v0.0.4"
  nameOverride: kube-vip-cloud-provider

vsphere-csi-driver:
  containerSecurityContext:
    allowPrivilegeEscalation: true
    capabilities:
      drop:
        - ALL
    runAsNonRoot: false
    seccompProfile:
      type: RuntimeDefault

  podSecurityContext:
    runAsNonRoot: false
    seccompProfile:
      type: RuntimeDefault
