global:
  config:
    enabled: true
    clusterId: ""
    vcenter: ""
    username: ""
    password: ""
    datacenter: ""
    region: ""
    zone: ""
    # openssl s_client -connect <vcenter>:443 < /dev/null 2>/dev/null | openssl x509 -fingerprint -sha1 -noout
    thumbprint: ""

  podSecurityStandards:
    enforced: false

cloud-provider-for-vsphere:
  daemonset:
    image: gsoci.azurecr.io/giantswarm/cpi-vsphere-manager
    tag: v1.26.2

kube-vip:
  enabled: true
  env:
    vip_interface: "ens192"
  image:
    repository: gsoci.azurecr.io/giantswarm/kube-vip
    tag: v0.8.0
  nameOverride: kube-vip-svc-lb
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
    operator: Exists
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists

kube-vip-cloud-provider:
  enabled: true
  rangeGlobal: ""
  cidrGlobal: ""
  image:
    repository: gsoci.azurecr.io/giantswarm/kube-vip-cloud-provider
    tag: v0.0.9
  nameOverride: kube-vip-cloud-provider

vsphere-csi-driver:
  containerSecurityContext:
    allowPrivilegeEscalation: true
    capabilities:
      drop:
        - ALL
    runAsNonRoot: false
    seccompProfile:
      type: RuntimeDefault

  controllerDeployment:
    csiAttacher:
      image: gsoci.azurecr.io/giantswarm/csi-attacher
      tag: v4.3.0
    csiResizer:
      image: gsoci.azurecr.io/giantswarm/csi-resizer
      tag: v1.8.0
    csiController:
      image: gsoci.azurecr.io/giantswarm/csi-vsphere-driver
      tag: v3.1.2
    livenessProbe:
      image: gsoci.azurecr.io/giantswarm/livenessprobe
      tag: v2.10.0
    syncer:
      image: gsoci.azurecr.io/giantswarm/csi-vsphere-syncer
      tag: v3.1.2
    csiProvisioner:
      image: gsoci.azurecr.io/giantswarm/csi-provisioner
      tag: v3.5.0
    csiSnapshotter:
      image: gsoci.azurecr.io/giantswarm/csi-snapshotter
      tag: v6.2.2

  nodeDaemonset:
    csiNode:
      image: gsoci.azurecr.io/giantswarm/csi-vsphere-driver
      tag: v3.1.2
    livenessProbe:
      image: gsoci.azurecr.io/giantswarm/livenessprobe
      tag: v2.10.0
    nodeDriverRegistrar:
      image: gsoci.azurecr.io/giantswarm/csi-node-driver-registrar
      tag: v2.8.0

  podSecurityContext:
    runAsNonRoot: false
    seccompProfile:
      type: RuntimeDefault
