apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    vsphere-cpi-infra:  common-configmap
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
data:
  api.binding: "{{ template "api.binding" . }}"
