{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  {{- if .Values.ingress.annotations }}
  annotations:
  {{- toYaml .Values.ingress.annotations | indent 4 }}
  {{- end }}
  labels:
    vsphere-cpi-infra: ingress
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}  
spec:
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ include "resource.default.name" . }}
              servicePort: {{ .Values.service.endpointPort }}
    {{- end -}}
  {{- if .Values.ingress.tls }}
  tls:
  {{- toYaml .Values.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
