apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    vsphere-cpi-infra: role-binding
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}-servicecatalog.k8s.io:apiserver-authentication-reader
  namespace: {{ include "resource.default.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ include "resource.default.name" . }}
    namespace: {{ include "resource.default.namespace" . }}
  - apiGroup: ""
    kind: User
    name: {{ include "resource.default.name" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "resource.default.name" . }}-system:cloud-controller-manager
  labels:
    vsphere-cpi-infra: cluster-role-binding
    {{- include "labels.common" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "resource.default.name" . }}-system:cloud-controller-manager
subjects:
  - kind: ServiceAccount
    name: {{ include "resource.default.name" . }}
    namespace: {{ include "resource.default.namespace" . }}
  - kind: User
    name: {{ include "resource.default.name" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "resource.default.name" . }}-system:cloud-controller-manager
  labels:
    vsphere-cpi-infra: role
    {{- include "labels.common" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - nodes/status
  verbs:
  - patch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services/status
  verbs:
  - patch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - get
  - list
  - watch
  - update
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - create
  - get
  - list
  - watch
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
