apiVersion: v1
kind: Secret
metadata:
  labels:
    vsphere-cpi-infra: secret
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}-cloud-secret
  namespace: {{ include "resource.default.namespace" . }}
stringData:
  {{ .Values.config.vcenter }}.username: {{ .Values.config.username | b64enc | quote }}
  {{ .Values.config.vcenter }}.password: {{ .Values.config.password | b64enc | quote }}
