{{- if .Values.config.enabled | default .Values.global.config.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: vsphere-cloud-secret
  labels:
    app: {{ template "cpi.name" . }}
    vsphere-cpi-infra: secret
    component: cloud-controller-manager
    {{- include "labels.common" $ | nindent 4 }}
  namespace: {{ .Release.Namespace }}
stringData:
  username: {{ .Values.config.username | default .Values.global.config.username }}
  password: {{ .Values.config.password | default .Values.global.config.password }}
{{- end -}}
