{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  {{- if .Values.service.annotations }}
  annotations:
  {{- toYaml .Values.service.annotations | indent 4 }}
  {{- end }}
  labels:
    giantswarm.io/monitoring: "true"
    vsphere-cpi-infra: service
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
spec:
  ports:
  - name: cpi-api
    port: {{ .Values.service.endpointPort }}
    protocol: TCP
    targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "labels.selector" . | nindent 6 }}
  type: {{ .Values.service.type }}
{{- template "loadBalancerSourceRanges" .Values }}
{{- end -}}
