{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels:
    app: {{ template "cpi.name" . }}
    vsphere-cpi-infra: service-account
    component: cloud-controller-manager
    {{- include "labels.common" $ | nindent 4 }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
