name: check generated yamls

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  check:
    name: check generated yamls
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip-ci') }}
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # tag=v4.1.0
    - name: generate manifests
      run: make all
    - name: check no change
      run: git diff --quiet --exit-code && [ -z "$(git status --porcelain)" ]
