{{- if .Values.global.kyvernoPolicyExceptions.enabled }}
apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: kube-vip-cloud-provider-exceptions
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  exceptions:
  - policyName: disallow-host-path
    ruleNames:
    - autogen-host-path
    - host-path
  - policyName: disallow-host-namespaces
    ruleNames:
    - host-namespaces
    - autogen-host-namespaces
  - policyName: restrict-seccomp-strict
    ruleNames:
    - check-seccomp-strict
    - autogen-check-seccomp-strict
  match:
    any:
    - resources:
        kinds:
        - Deployment
        - ReplicaSet
        - Pod
        namespaces:
        - {{ .Release.Namespace }}
        names:
        - kube-vip-cloud-provider*
{{- end }}
